const { contextBridge, ipcRenderer } = require('electron')

contextBridge.exposeInMainWorld('electronAPI', {
  resizeWindow: (width, height) => ipcRenderer.send('resize-window', width, height),
  getScreenInfo: () => ipcRenderer.invoke('get-screen-info'),
  setWindowSize: (userId, width, height) => ipcRenderer.invoke('set-window-size', userId, width, height),
  getWindowSize: (userId) => ipcRenderer.invoke('get-window-size', userId),
  applyWindowSize: (userId) => ipcRenderer.invoke('apply-window-size', userId),
  onUpdateStatus: (callback) => ipcRenderer.on('update-status', (_event, data) => callback(data)),
  checkForUpdate: () => ipcRenderer.invoke('check-for-update'),
  openExternal: (url) => ipcRenderer.invoke('open-external', url),
  saveFileDialog: (options) => ipcRenderer.invoke('save-file-dialog', options),
  openFileDialog: (options) => ipcRenderer.invoke('open-file-dialog', options),
  readFile: (filePath) => ipcRenderer.invoke('read-file', filePath),
  writeFile: (filePath, content) => ipcRenderer.invoke('write-file', filePath, content),
  restartApp: () => ipcRenderer.send('restart-app'),
  getLogFileSize: () => ipcRenderer.invoke('get-log-file-size'),
  getLogDirSize: () => ipcRenderer.invoke('get-log-dir-size'),
  getDataDirSize: () => ipcRenderer.invoke('get-data-dir-size'),
  getLogContent: () => ipcRenderer.invoke('get-log-content'),
  clearLogs: () => ipcRenderer.invoke('clear-logs'),
  openLogViewer: (content) => ipcRenderer.invoke('open-log-viewer', content),
  getModuleSizes: () => ipcRenderer.invoke('get-module-sizes'),
  openCleanDataWindow: (data) => ipcRenderer.invoke('open-clean-data-window', data),
  confirmCleanData: (result) => ipcRenderer.send('clean-data-confirm', result),
  cancelCleanData: () => ipcRenderer.send('clean-data-cancel'),
  checkVersionUpdate: (userId) => ipcRenderer.invoke('check-version-update', userId),
  openChangelogWindow: (content) => ipcRenderer.invoke('open-changelog-window', content),
  scheduleReminders: (reminders, persistDuration) => ipcRenderer.invoke('schedule-reminders', reminders, persistDuration),
  cancelAllReminders: () => ipcRenderer.invoke('cancel-all-reminders'),
  getReminderPersistDuration: () => ipcRenderer.invoke('get-reminder-persist-duration'),
      getAllReminders: () => ipcRenderer.invoke('get-all-reminders'),
  onShowReminder: (callback) => ipcRenderer.on('show-reminder', (_event, data) => callback(data)),
  setAutoLaunch: (enable) => ipcRenderer.invoke('set-auto-launch', enable),
  getAutoLaunch: () => ipcRenderer.invoke('get-auto-launch'),
  setCloseAction: (action) => ipcRenderer.invoke('set-close-action', action),
  getCloseAction: () => ipcRenderer.invoke('get-close-action'),

  // 文件管理器
  getDataDirPath: () => ipcRenderer.invoke('get-data-dir-path'),
  getLogDirPath: () => ipcRenderer.invoke('get-log-dir-path'),
  readDirectory: (dirPath) => ipcRenderer.invoke('read-directory', dirPath),
  deleteFilePath: (filePath) => ipcRenderer.invoke('delete-file-path', filePath),
  renameFilePath: (oldPath, newPath) => ipcRenderer.invoke('rename-file-path', oldPath, newPath),
  readTextFilePath: (filePath) => ipcRenderer.invoke('read-text-file-path', filePath),

  // 局域网传输
  startLanServer: (data) => ipcRenderer.invoke('start-lan-server', data),
  stopLanServer: () => ipcRenderer.invoke('stop-lan-server'),
  fetchLanData: (url) => ipcRenderer.invoke('fetch-lan-data', url)
})