directories:
  output: release
  buildResources: build
appId: com.earth-survival-diary.app
productName: 地球 Online 生存日记
files:
  - filter:
      - dist/**/*
      - electron/**/*
      - build/**/*
      - package.json
      - '!node_modules/**/*'
extraResources:
  - from: build/icon.png
    to: build/icon.png
  - from: build/icon.ico
    to: build/icon.ico
  - from: electron/node_modules
    to: node_modules
win:
  icon: build/icon.ico
  target: nsis
publish:
  provider: github
  channel: latest
electronVersion: 41.10.3
